# Generated by Django 5.0.6 on 2024-06-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_profession_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
